//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectweekWPF.TussentijdsProjectYannick
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeelslid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeelslid()
        {
            this.Bestellings = new HashSet<Bestelling>();
        }
    
        public int PersoneelslidID { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Wachtwoord { get; set; }
        public int AdminRechtenID { get; set; }
        public string Salt { get; set; }
        public string Username { get; set; }
        public System.DateTime Indiensttreding { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestellings { get; set; }
        public virtual AdminRechten AdminRechten { get; set; }
    }
}
